### ISSUE TITLE
프론트 추가 요구사항

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#101]
Discussion : [link](https://github.com/orgs/Project-MO-A/discussions/12)

## TODO
- [x] Admin : GET /recruitment/{recruitmentId}/approved/members id값 추가
- [x] Admin : GET /recruitment/{recruitmentId}/apply/members?statusCode 빈 배열 시 에러로 반환 됨
- [x] Admin : 리더 상태 변환 가능 문제 수정
- [x] RecruitMember : 모집글 count가 0으로 나오는 문제 수정
- [x] PossibleTime : PUT /recruitment/{recruitmentId}/time 500 Error
- [x] ApplimentMember : 중복 신청 가능 문제 수정
- [x] Recruitment : 모집글 수정 필드에 categoryName 추가

**Comment by Juhongseok** [comment]
두 번째는 에러가 아니라 그냥 단순 빈 배열 넘겨줘도 될 거 같아요
세 번째는 redirect가 문제일까요??

**Comment by KAispread** [comment]
> 두 번째는 에러가 아니라 그냥 단순 빈 배열 넘겨줘도 될 거 같아요 세 번째는 redirect가 문제일까요??

두 번째는 빈 배열 넘어가도록 변경했습니다.
세 번째 에러는 Axios 에러가 뜨는걸로 봐서 뭔가 다른 문제가 있는 것 같은데 찾아볼게요
