### ISSUE TITLE
프론트 추가 요구사항

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#102]
Discussion : [link](https://github.com/orgs/Project-MO-A/discussions/12)

## TODO
- [x] User : GET /user/info/activity 500 Error
    - [x] etcProjects에 recruitmentId 추가
- [x] User : GET /user/info/profile userId 추가
