### ISSUE TITLE
Test용 EC2 인스턴스 서버 구동

### ISSUE THREAD

**Issue by KAispread** [Project-MO-A/Backend#65]
## TODO
- [x] VPC 생성 (Public, Private subnet 생성)
- [x] EC2 인스턴스 생성
- [x] 애플리케이션 서버 구동

**Comment by Juhongseok** [comment]
@KAispread 
[램스왑](https://velog.io/@shawnhansh/AWS-EC2-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%8A%A4%EC%99%91)적용하는 방법 포스팅 된 정보이에요

**Comment by Juhongseok** [comment]
@KAispread 
[램스왑](https://velog.io/@shawnhansh/AWS-EC2-%EB%A9%94%EB%AA%A8%EB%A6%AC-%EC%8A%A4%EC%99%91)적용하는 방법 포스팅 된 정보이에요

**Comment by Juhongseok** [comment]
삽질 목록

- application.yml 분리
- submodule 
- ec2, rds 연결
- rds테이블
- application.yml active, datasource url prefix jdbc:mysql://
- security group 3306
