### ISSUE TITLE
추가 확인 사항

### ISSUE THREAD

**Issue by Juhongseok** [Project-MO-A/Backend#77]
## TODO
- [x] 프론트 서버 cors 설정
- [x] 인기 글 10개로 증가
- [x] 추천 글 기본 12개 나머지 스크롤링
- [x] 회원 가입, 로그인 에러 확인
- [x] 회원 탈퇴 Endpoint 값 변경
